# my_nbooks


<!-- WARNING: THIS FILE WAS AUTOGENERATED! DO NOT EDIT! -->

This file will become your README and also the index of your
documentation.

## Install

``` sh
pip install my_nbooks
```

## How to use

Fill me in please! Donâ€™t forget code examples:

``` python
# say(11)
```

``` python
import os
os.getcwd()
```

    'C:\\Users\\Administrator\\Documents\\WeChat Files\\wxid_fje5vggkvjg912\\FileStorage\\File\\2024-06\\my_nbooks\\my_nbooks\\nbs'

``` python
import sys

# sys.path.append('e:\\proj\\my_nbooks\\my_nbooks\\core.py')
```

``` python
sys.path
```

    ['D:\\programesx64\\Anaconda3\\envs\\mykaggle\\python39.zip',
     'D:\\programesx64\\Anaconda3\\envs\\mykaggle\\DLLs',
     'D:\\programesx64\\Anaconda3\\envs\\mykaggle\\lib',
     'D:\\programesx64\\Anaconda3\\envs\\mykaggle',
     '',
     'C:\\Users\\Administrator\\AppData\\Roaming\\Python\\Python39\\site-packages',
     'D:\\programesx64\\Anaconda3\\envs\\mykaggle\\lib\\site-packages',
     'e:\\proj\\my_nbooks',
     'D:\\programesx64\\Anaconda3\\envs\\mykaggle\\lib\\site-packages\\win32',
     'D:\\programesx64\\Anaconda3\\envs\\mykaggle\\lib\\site-packages\\win32\\lib',
     'D:\\programesx64\\Anaconda3\\envs\\mykaggle\\lib\\site-packages\\Pythonwin']

``` python
code_extract2('[INST]Write Python code to solve this problem in a brute force manner. You will only print the final result.\n\nFind the largest two digit prime number which is also a prime number when the digits are reversed.\n\nReminder: You will write Python code. You do not care about the efficiency of the solution, you will only care about the correctness.[/INST] Here is a brute force solution to find the largest two digit prime number which is also a prime number when the digits are reversed:\n\n```python\ndef is\\_prime(n):\nfor i in range(2, int(n**0.5) + 1):\nif n % i == 0:\nreturn False\nreturn True\n\nlargest\\_prime = -1\n')
```

    ''

``` python
# say(11)
```

    NameError: name 'say' is not defined
    [1;31m---------------------------------------------------------------------------[0m
    [1;31mNameError[0m                                 Traceback (most recent call last)
    Cell [1;32mIn[5], line 1[0m
    [1;32m----> 1[0m [43msay[49m([38;5;241m11[39m)

    [1;31mNameError[0m: name 'say' is not defined
